CREATE DATABASE IF NOT EXISTS `portfolio`
DEFAULT CHARACTER SET latin1
COLLATE latin1_swedish_ci;
USE `portfolio`;
CREATE TABLE IF NOT EXISTS `user` ( 
  `Id` INT(11) NOT NULL AUTO_INCREMENT, 
  `Name` VARCHAR(150) NOT NULL,  
  `Mail` VARCHAR(150) NOT NULL, 
  `Mess` TEXT NOT NULL,
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1;